version: "3.7"

services:
  react:
    container_name: react
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  firebase:
    container_name: firebase
    build:
      context: ./functions/kku-smart-farm/functions
      dockerfile: Dockerfile
    ports:
      - 5001:5000