version: "3.7"

volumes:
 firebase-node_modules:
 firebase-lib:
 react-node_modules:
 
services:
  react:
    container_name: react
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "react-node_modules:/app/node_modules"
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  firebase:
   build: ./firebase/functions
   image: firebase
   container_name: firebase
   ports:
     - 4000:4000
     - 5001:5001
     - 5002:5002
     - 8080:8080
   volumes:
     - ./firebase:/firebase
     - firebase-lib:/firebase/functions/lib
     - firebase-node_modules:/firebase/functions/node_modules
   environment:
     - FIREBASE_PROJECT
     - FIREBASE_TOKEN